version: '3.9'

services:
  go-app:
    container_name: go-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
    volumes:
      - .:/app
    restart: unless-stopped
  go_db:
    container_name: go_db
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      - go_db
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@go_db:5432/postgres?sslmode=disable",
      "up"
    ]
    restart: on-failure

volumes:
  pgdata: {}