basePath: /
definitions:
  models.CartItemResponse:
    description: Details of a cart item in the response.
    properties:
      added_at:
        description: Timestamp when the product was added to the cart
        example: "2023-08-01T12:00:00Z"
        type: string
      price:
        description: Price of the product at the time it was added
        example: 199.99
        type: number
      product_id:
        description: Product ID
        example: 101
        type: integer
      quantity:
        description: Quantity of the product
        example: 2
        type: integer
      user_id:
        description: User ID
        example: 1
        type: integer
    type: object
  models.Category:
    properties:
      id:
        example: 1
        type: integer
      name:
        example: Electronics
        type: string
      slug:
        example: electronics
        type: string
    type: object
  models.CreateCartItemRequest:
    description: Input for adding a product to the cart.
    properties:
      product_id:
        description: Product ID
        example: 101
        type: integer
      quantity:
        description: Quantity of the product
        example: 2
        type: integer
    type: object
  models.CreateCategoryRequest:
    properties:
      name:
        example: Electronics
        type: string
      slug:
        example: electronics
        type: string
    type: object
  models.CreateProductRequest:
    description: A product contains details like name, description, price, stock,
      category, and image URL.
    properties:
      category_id:
        example: 3
        type: integer
      description:
        example: A brand-new smartphone with advanced features
        type: string
      image_url:
        example: https://example.com/smartphone.jpg
        type: string
      name:
        example: Nokia
        type: string
      price:
        example: 799.99
        type: number
      stock:
        example: 100
        type: integer
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.Order:
    description: An order contains details like user ID, total price, status, and
      the time it was placed.
    properties:
      id:
        description: Order ID
        example: 1
        type: integer
      placed_at:
        description: Timestamp when the order was placed
        example: "2023-08-01T12:00:00Z"
        type: string
      status:
        description: Status of the order
        example: Pending
        type: string
      total_price:
        description: Total Price of the order
        example: 299.99
        type: number
      user_id:
        description: User ID
        example: 101
        type: integer
    type: object
  models.OrderResponse:
    description: Details of an order in the response.
    properties:
      id:
        description: Order ID
        example: 1
        type: integer
      items:
        description: List of ordered items
        items:
          $ref: '#/definitions/models.OrderedItem'
        type: array
      placed_at:
        description: Timestamp when the order was placed
        example: "2023-08-01T12:00:00Z"
        type: string
      status:
        description: Status of the order
        example: Pending
        type: string
      total_price:
        description: Total Price of the order
        example: 299.99
        type: number
      user_id:
        description: User ID
        example: 101
        type: integer
    type: object
  models.OrderedItem:
    description: An ordered item contains details about the product, quantity, price,
      and the order it belongs to.
    properties:
      id:
        description: Ordered Item ID
        example: 1
        type: integer
      order_id:
        description: Order ID
        example: 1
        type: integer
      price:
        description: Price of the product at the time of the order
        example: 149.99
        type: number
      product_id:
        description: Product ID
        example: 101
        type: integer
      quantity:
        description: Quantity of the product
        example: 2
        type: integer
    type: object
  models.Product:
    properties:
      category_id:
        description: ID of the category the product belongs to
        example: 2
        type: integer
      created_at:
        description: Timestamp when the product was created
        example: "2023-08-01T12:00:00Z"
        type: string
      description:
        description: Product Description
        example: A high-performance laptop
        type: string
      id:
        description: Product ID
        example: 1
        type: integer
      image_url:
        description: URL of the product image
        example: https://example.com/image.jpg
        type: string
      name:
        description: Product Name
        example: Lenovo 96
        type: string
      price:
        description: Price of the Product
        example: 999.99
        type: number
      stock:
        description: Number of Stocks
        example: 50
        type: integer
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  models.UpdateProductRequest:
    description: A product contains details like name, description, price, stock,
      category, and image URL.
    properties:
      category_id:
        example: 3
        type: integer
      description:
        example: A brand-new smartphone with advanced features
        type: string
      image_url:
        example: https://example.com/smartphone.jpg
        type: string
      name:
        example: Nokia
        type: string
      price:
        example: 799.99
        type: number
      stock:
        example: 100
        type: integer
    type: object
  models.User:
    properties:
      address:
        description: Optional / new fields
        type: string
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      last_login:
        type: string
      name:
        type: string
      phone:
        type: string
      role:
        description: user or admin
        type: string
      status:
        description: active, inactive, suspended
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a RESTful API for an E-commerce platform built with Go.
  title: GO Commerce API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: '"Check if server is running fine"'
      produces:
      - application/json
      responses:
        "200":
          description: All good
          schema:
            type: string
      summary: Ping
      tags:
      - Ping
  /api/cart:
    get:
      description: Retrieve all items in the user's cart
      parameters:
      - description: Bearer + JWT_Token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CartItemResponse'
            type: array
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Get Cart Items
      tags:
      - Cart
    post:
      consumes:
      - application/json
      description: Remove a product to the user's cart
      parameters:
      - description: Bearer + JWT_Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CartItemResponse'
        "400":
          description: Invalid Input
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Remove from cart
      tags:
      - Cart
  /api/categories:
    get:
      consumes:
      - application/json
      description: Retrieve all categories
      parameters:
      - description: Bearer + admin_JWT_Token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get All Categories
      tags:
      - Categories
    post:
      consumes:
      - application/json
      description: Create a new category
      parameters:
      - description: Bearer + admin_JWT_Token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Category Input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreateCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CreateCategoryRequest'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create Category
      tags:
      - Categories
  /api/orders:
    get:
      description: Retrieve all orders placed by the user
      parameters:
      - description: Bearer JWT_Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.OrderResponse'
            type: array
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Get Orders
      tags:
      - Orders
  /api/orders/checkout:
    post:
      consumes:
      - application/json
      description: Place a new order with the items in the user's cart
      parameters:
      - description: Bearer + JWT_Token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Order Input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Order'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.OrderResponse'
        "400":
          description: Invalid Input
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Place Order
      tags:
      - Orders
  /api/products:
    get:
      consumes:
      - application/json
      description: Get all the products from db
      parameters:
      - description: Bearer + JWT_Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get All Products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create a new product
      parameters:
      - description: Bearer + JWT_Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Product Input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Invalid Input
          schema:
            type: string
        "402":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Create Product
      tags:
      - Products
  /api/products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a product by ID
      parameters:
      - description: Bearer + JWT_Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad request
          schema:
            type: string
      summary: Delete Product
      tags:
      - Products
    get:
      consumes:
      - application/json
      description: Get a single product by ID
      parameters:
      - description: Bearer + JWT_Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get One Products
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Update a product by ID
      parameters:
      - description: Bearer + JWT_Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product Input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UpdateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad request
          schema:
            type: string
      summary: Update Product
      tags:
      - Products
  /api/users:
    get:
      consumes:
      - application/json
      description: Get all the users from db
      parameters:
      - description: Bearer + JWT_Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get All Users
      tags:
      - User
  /api/users/email/{email}:
    get:
      consumes:
      - application/json
      description: Get a single user from db
      parameters:
      - description: Bearer + JWT_Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User Email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get Single Users By Email
      tags:
      - User
  /api/users/id/{id}:
    get:
      consumes:
      - application/json
      description: Get a single user from db
      parameters:
      - description: Bearer + JWT_Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get Single Users by ID
      tags:
      - User
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login to your user account
      parameters:
      - description: Login Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Invalid Input
          schema:
            type: string
        "401":
          description: Wrong Email or password
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a user
      parameters:
      - description: Registration credential
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Invalid Input
          schema:
            type: string
      summary: Register
      tags:
      - Auth
swagger: "2.0"
